import React, { createContext, useContext, useState, useEffect } from 'react';
import { useAuth } from './AuthContext';

type Language = 'en' | 'hi' | 'kn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Issue/Feedback Detail
    'issue.details': 'Issue Details',
    'issue.recommendedTraining': 'Recommended Training',
    'issue.findingModule': 'Finding best module...',
    'issue.basedOnReport': 'Based on your report',
    'issue.startTraining': 'Start Training Module',
    'issue.yourReport': 'Your Report',
    
    // History
    'history.title': 'My Feedback',
    'history.issues': 'issues',
    'history.issue': 'issue',
    'history.allStatus': 'All Status',
    'history.filter': 'Filter',
    'history.trainingAssigned': 'Training Assigned',
    'history.noFeedback': 'No feedback yet',
    'history.noMatching': 'No matching feedback',
    'history.startReporting': 'Start by reporting your first issue',
    'history.tryFilter': 'Try changing the filter to see more results',
    'history.reportIssue': 'Report an Issue',
    
    // Login
    'login.title': 'GuruSikshan',
    'login.subtitle': 'School Feedback System',
    'login.signIn': 'Sign in',
    'login.enterCredentials': 'Enter your credentials to continue',
    'login.email': 'Email',
    'login.emailPlaceholder': 'teacher@school.edu',
    'login.emailRequired': 'Email is required',
    'login.emailInvalid': 'Please enter a valid email',
    'login.password': 'Password',
    'login.passwordPlaceholder': 'Enter your password',
    'login.passwordRequired': 'Password is required',
    'login.passwordMin': 'Password must be at least 4 characters',
    'login.signingIn': 'Signing in...',
    'login.signInButton': 'Sign in',
    'login.demoHint': 'Use any email and password (min 4 chars) to login',
    'login.welcomeBack': 'Welcome back!',
    'login.loginSuccess': 'You\'ve successfully logged in.',
    'login.loginFailed': 'Login failed',
    'login.checkCredentials': 'Please check your credentials and try again.',
    'login.connectionError': 'Connection error',
    'login.networkError': 'Unable to connect. Please check your network.',
    
    // Not Found
    'notFound.title': '404',
    'notFound.message': 'Oops! Page not found',
    'notFound.returnHome': 'Return to Home',
    
    // Onboarding
    'onboarding.skip': 'Skip',
    'onboarding.next': 'Next',
    'onboarding.getStarted': 'Get Started',
    'onboarding.slide1.title': 'Report Issues Easily',
    'onboarding.slide1.desc': 'Submit feedback about any school-related issues directly from your phone. Academic, infrastructure, safety – we\'ve got you covered.',
    'onboarding.slide2.title': 'Track Your Submissions',
    'onboarding.slide2.desc': 'Stay informed about the status of your reported issues. Get updates when your feedback is being reviewed or resolved.',
    'onboarding.slide3.title': 'Real-time Updates',
    'onboarding.slide3.desc': 'Receive notifications when there are updates on your submitted feedback. No more wondering about the status.',
    'onboarding.slide4.title': 'See Results',
    'onboarding.slide4.desc': 'View resolution details and admin remarks. Your voice matters and leads to real improvements in the school.',
    
    // Report Issue
    'report.reportingAs': 'Reporting as',
    'report.descriptionLabel': 'Description',
    'report.descriptionPlaceholder': 'Describe the issue in detail...',
    'report.descriptionRequired': 'Description is required',
    'report.descriptionMin': 'Please provide at least 20 characters',
    'report.categoryRequired': 'Please select a category',
    'report.submitButton': 'Submit Issue',
    'report.submitting': 'Submitting...',
    'report.alreadyAssigned': 'Training Already Assigned!',
    'report.checkTraining': 'Check your Training tab to continue.',
    'report.issueReported': 'Issue Reported!',
    'report.submittedSuccess': 'Your Issue has been submitted successfully.',
    'report.personalizedAssigned': 'Personalized training assigned!',
    'report.submitSuccess': 'Issue reported successfully!',
    'report.submitFailed': 'Failed to submit',
    'report.checkConnection': 'Please check your connection and try again.',
    
    // Training
    'training.myTraining': 'My Training',
    'training.loadingTrainings': 'Loading your trainings...',
    'training.new': 'New',
    'training.active': 'Active',
    'training.done': 'Done',
    'training.all': 'All',
    'training.unnamed': 'Unnamed Training',
    'training.noDescription': 'No description available',
    'training.completedOn': 'Completed',
    'training.overdueBy': 'Overdue by',
    'training.days': 'days',
    'training.dueToday': 'Due today',
    'training.dueIn': 'Due in',
    'training.difficulty': 'Difficulty',
    'training.duration': 'Duration',
    'training.noTrainings': 'No trainings found',
    'training.trySwitching': 'Try switching to another tab',
    
    // Training Detail
    'trainingDetail.back': 'Back',
    'trainingDetail.trainingDetails': 'Training Details',
    'trainingDetail.notFound': 'Training not found',
    'trainingDetail.yourProgress': 'Your Progress',
    'trainingDetail.completion': 'Completion',
    'trainingDetail.updateProgress': 'Update your progress:',
    'trainingDetail.markComplete': 'Mark as Complete',
    'trainingDetail.completedOn': 'Completed on',
    'trainingDetail.trainingContent': 'Training Content',
    'trainingDetail.noContent': 'No content available',
    'trainingDetail.watchVideo': 'Watch Training Video',
    'trainingDetail.trainingInfo': 'Training Information',
    'trainingDetail.assignedOn': 'Assigned on:',
    'trainingDetail.dueDate': 'Due date:',
    'trainingDetail.daysOverdue': 'days overdue',
    'trainingDetail.daysRemaining': 'days remaining',
    'trainingDetail.shareFeedback': 'Share Feedback on Training',
    'trainingDetail.completeToFeedback': 'Complete training to provide feedback',
    
    // Training Feedback
    'feedback.trainingComplete': 'Training Complete!',
    'feedback.rateTraining': 'How would you rate this training?',
    'feedback.tapToRate': 'Tap to rate',
    'feedback.poor': 'Poor',
    'feedback.fair': 'Fair',
    'feedback.good': 'Good',
    'feedback.veryGood': 'Very Good',
    'feedback.excellent': 'Excellent',
    'feedback.helpSolve': 'Did this help solve your issue?',
    'feedback.yes': 'Yes',
    'feedback.no': 'No',
    'feedback.additionalFeedback': 'Any additional feedback?',
    'feedback.optional': 'Optional',
    'feedback.placeholder': 'Share your thoughts, suggestions, or what you learned...',
    'feedback.submitButton': 'Submit Feedback',
    'feedback.submittingButton': 'Submitting...',
    'feedback.provideRating': 'Please provide a rating and indicate if the training was helpful',
    'feedback.thankYou': 'Thank you!',
    'feedback.submitted': 'Your feedback has been submitted',
    'feedback.submissionFailed': 'Submission Failed',
    'feedback.missingInfo': 'Missing required information',
    'feedback.completeForm': 'Please complete the form',
    'feedback.ratingRequired': 'Rating and helpfulness are required',
    
    // Tutorial
    'tutorial.skipTutorial': 'Skip Tutorial',
    'tutorial.of': 'of',
    'tutorial.previous': 'Previous',
    'tutorial.next': 'Next',
    'tutorial.getStarted': 'Get Started',
    'tutorial.welcome.title': 'Welcome to TeacherVoice',
    'tutorial.welcome.desc': 'Your platform for reporting school issues and tracking their resolution.',
    'tutorial.reporting.title': 'Reporting Issues',
    'tutorial.reporting.desc': 'Learn how to submit and track school-related issues.',
    'tutorial.training.title': 'Training Modules',
    'tutorial.training.desc': 'Access and complete your assigned training materials.',
    'tutorial.history.title': 'Your History',
    'tutorial.history.desc': 'Review all your submitted feedback and their current status.',
    'tutorial.profile.title': 'Profile & Settings',
    'tutorial.profile.desc': 'Customize your experience and manage your profile.',
    'tutorial.feedback.title': 'Providing Feedback',
    'tutorial.feedback.desc': 'Share your thoughts on completed trainings.',
    
    // Settings (additional)
    'settings.preferences': 'Preferences',
    'settings.darkMode': 'Dark Mode',
    'settings.useDarkTheme': 'Use dark theme',
    'settings.notifications': 'Notifications',
    'settings.receiveUpdates': 'Receive status updates',
    'settings.supportInfo': 'Support & Information',
    'settings.appTutorial': 'App Tutorial',
    'settings.contactSupport': 'Contact Support',
    'settings.privacyPolicy': 'Privacy Policy',
    'settings.version': 'TeacherVoice v1.0.0',
    'settings.loggedOut': 'Logged out',
    'settings.logoutSuccess': 'You\'ve been successfully logged out.',

    'profile.editProfile': 'Edit Profile',
    'profile.changePhoto': 'Tap to change photo',
    'profile.personalInfo': 'Personal Information',
    'profile.fullName': 'Full Name',
    'profile.fullNamePlaceholder': 'Enter your full name',
    'profile.emailAddress': 'Email Address',
    'profile.emailPlaceholder': 'Enter your email',
    'profile.emailCannotChange': 'Email cannot be changed',
    'profile.phoneNumber': 'Phone Number',
    'profile.phonePlaceholder': 'Enter your phone number',
    'profile.bio': 'Bio',
    'profile.bioPlaceholder': 'Tell us about yourself...',
    'profile.professionalInfo': 'Professional Information',
    'profile.qualification': 'Qualification',
    'profile.qualificationPlaceholder': 'Your qualifications',
    'profile.experience': 'Years of Experience',
    'profile.experiencePlaceholder': 'Years of experience',
    'profile.subjects': 'Subjects Taught',
    'profile.subjectsPlaceholder': 'Subjects you teach',
    'profile.assignedCluster': 'Assigned Cluster',
    'profile.clusterPlaceholder': 'Your assigned cluster',
    'profile.contactAdminCluster': 'Contact admin to change cluster',
    'profile.updateSuccess': 'Profile Updated',
    'profile.updateSuccessMsg': 'Your profile has been successfully updated.',

    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.report': 'Report Issue',
    'nav.history': 'History',
    'nav.training': 'Training',
    'nav.settings': 'Settings',
    
    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.pending': 'Pending',
    'dashboard.resolved': 'Resolved',
    'dashboard.training': 'Training',
    'dashboard.recentIssues': 'Recent Issues',
    'dashboard.noIssues': 'No issues reported yet',
    'dashboard.viewAll': 'View All',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.reportNew': 'Report an Issue',
    'dashboard.viewHistory': 'View History',
    'dashboard.reviewed': 'Reviewed',
    'dashboard.recentActivity': 'Recent Activity',
    
    // Report Issue
    'report.title': 'Report Issue',
    'report.subtitle': 'Describe the challenge you\'re facing',
    'report.cluster': 'Cluster',
    'report.category': 'Category',
    'report.description': 'Description',
    'report.submit': 'Submit Report',
    'report.success': 'Issue Reported',
    'report.successMsg': 'Your issue has been submitted successfully',
    
    // Categories
    'category.academic': 'Academic',
    'category.infrastructure': 'Infrastructure',
    'category.administrative': 'Administrative',
    'category.safety': 'Safety',
    'category.technology': 'Technology',
    'category.other': 'Other',
    
    // Status
    'status.pending': 'Pending',
    'status.reviewed': 'Reviewed',
    'status.resolved': 'Resolved',
    'status.training_assigned': 'Training Assigned',
    
    // Training
    'training.title': 'My Training',
    'training.subtitle': 'Your assigned training modules',
    'training.notStarted': 'Not Started',
    'training.inProgress': 'In Progress',
    'training.completed': 'Completed',
    'training.noTraining': 'No training assigned yet',
    'training.startTraining': 'Start Training',
    'training.continueTraining': 'Continue Training',
    'training.viewDetails': 'View Details',
    'training.dueDate': 'Due Date',
    'training.progress': 'Progress',
    
    // Settings
    'settings.title': 'Settings',
    'settings.profile': 'Profile',
    'settings.language': 'Language',
    'settings.selectLanguage': 'Select Language',
    'settings.name': 'Name',
    'settings.email': 'Email',
    'settings.cluster': 'Cluster',
    'settings.employeeId': 'Employee ID',
    'settings.logout': 'Logout',
    'settings.editProfile': 'Edit Profile',
    
    // Common
    'common.back': 'Back',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.viewDetails': 'View Details',
    'common.close': 'Close',
    'common.saving': 'Saving...',
  },
  
  hi: {
    // Issue/Feedback Detail
    'issue.details': 'समस्या विवरण',
    'issue.recommendedTraining': 'अनुशंसित प्रशिक्षण',
    'issue.findingModule': 'सर्वोत्तम मॉड्यूल खोज रहे हैं...',
    'issue.basedOnReport': 'आपकी रिपोर्ट के आधार पर',
    'issue.startTraining': 'प्रशिक्षण मॉड्यूल शुरू करें',
    'issue.yourReport': 'आपकी रिपोर्ट',
    
    // History
    'history.title': 'मेरी फ़ीडबैक',
    'history.issues': 'समस्याएं',
    'history.issue': 'समस्या',
    'history.allStatus': 'सभी स्थिति',
    'history.filter': 'फ़िल्टर',
    'history.trainingAssigned': 'प्रशिक्षण दिया गया',
    'history.noFeedback': 'अभी तक कोई फ़ीडबैक नहीं',
    'history.noMatching': 'कोई मेल खाने वाली फ़ीडबैक नहीं',
    'history.startReporting': 'अपनी पहली समस्या दर्ज करके शुरुआत करें',
    'history.tryFilter': 'अधिक परिणाम देखने के लिए फ़िल्टर बदलें',
    'history.reportIssue': 'समस्या दर्ज करें',
    
    // Login
    'login.title': 'गुरुशिक्षण',
    'login.subtitle': 'स्कूल फ़ीडबैक प्रणाली',
    'login.signIn': 'साइन इन करें',
    'login.enterCredentials': 'जारी रखने के लिए अपनी साख दर्ज करें',
    'login.email': 'ईमेल',
    'login.emailPlaceholder': 'teacher@school.edu',
    'login.emailRequired': 'ईमेल आवश्यक है',
    'login.emailInvalid': 'कृपया एक वैध ईमेल दर्ज करें',
    'login.password': 'पासवर्ड',
    'login.passwordPlaceholder': 'अपना पासवर्ड दर्ज करें',
    'login.passwordRequired': 'पासवर्ड आवश्यक है',
    'login.passwordMin': 'पासवर्ड कम से कम 4 वर्णों का होना चाहिए',
    'login.signingIn': 'साइन इन हो रहा है...',
    'login.signInButton': 'साइन इन करें',
    'login.demoHint': 'लॉगिन करने के लिए कोई भी ईमेल और पासवर्ड (न्यूनतम 4 अक्षर) उपयोग करें',
    'login.welcomeBack': 'वापस स्वागत है!',
    'login.loginSuccess': 'आप सफलतापूर्वक लॉग इन हो गए हैं।',
    'login.loginFailed': 'लॉगिन विफल',
    'login.checkCredentials': 'कृपया अपनी साख जांचें और पुनः प्रयास करें।',
    'login.connectionError': 'कनेक्शन त्रुटि',
    'login.networkError': 'कनेक्ट करने में असमर्थ। कृपया अपना नेटवर्क जांचें।',
    
    // Not Found
    'notFound.title': '404',
    'notFound.message': 'ओह! पृष्ठ नहीं मिला',
    'notFound.returnHome': 'होम पर वापस जाएं',
    
    // Onboarding
    'onboarding.skip': 'छोड़ें',
    'onboarding.next': 'अगला',
    'onboarding.getStarted': 'शुरू करें',
    'onboarding.slide1.title': 'आसानी से समस्या दर्ज करें',
    'onboarding.slide1.desc': 'अपने फोन से सीधे किसी भी स्कूल संबंधी समस्या के बारे में फ़ीडबैक जमा करें। शैक्षणिक, बुनियादी ढांचा, सुरक्षा – हमने सब कवर किया है।',
    'onboarding.slide2.title': 'अपनी सबमिशन ट्रैक करें',
    'onboarding.slide2.desc': 'अपनी रिपोर्ट की गई समस्याओं की स्थिति के बारे में सूचित रहें। जब आपकी फ़ीडबैक की समीक्षा की जा रही हो या हल हो रही हो तो अपडेट प्राप्त करें।',
    'onboarding.slide3.title': 'वास्तविक समय अपडेट',
    'onboarding.slide3.desc': 'जब आपकी जमा की गई फ़ीडबैक पर अपडेट हों तो सूचनाएं प्राप्त करें। स्थिति के बारे में अब आश्चर्य न करें।',
    'onboarding.slide4.title': 'परिणाम देखें',
    'onboarding.slide4.desc': 'समाधान विवरण और व्यवस्थापक टिप्पणियां देखें। आपकी आवाज़ मायने रखती है और स्कूल में वास्तविक सुधार लाती है।',
    
    // Report Issue
    'report.reportingAs': 'इस रूप में रिपोर्ट कर रहे हैं',
    'report.descriptionLabel': 'विवरण',
    'report.descriptionPlaceholder': 'समस्या का विस्तार से वर्णन करें...',
    'report.descriptionRequired': 'विवरण आवश्यक है',
    'report.descriptionMin': 'कृपया कम से कम 20 वर्ण प्रदान करें',
    'report.categoryRequired': 'कृपया एक श्रेणी चुनें',
    'report.submitButton': 'समस्या जमा करें',
    'report.submitting': 'जमा किया जा रहा है...',
    'report.alreadyAssigned': 'प्रशिक्षण पहले से दिया गया!',
    'report.checkTraining': 'जारी रखने के लिए अपना प्रशिक्षण टैब देखें।',
    'report.issueReported': 'समस्या दर्ज की गई!',
    'report.submittedSuccess': 'आपकी समस्या सफलतापूर्वक जमा कर दी गई है।',
    'report.personalizedAssigned': 'व्यक्तिगत प्रशिक्षण दिया गया!',
    'report.submitSuccess': 'समस्या सफलतापूर्वक दर्ज की गई!',
    'report.submitFailed': 'जमा करने में विफल',
    'report.checkConnection': 'कृपया अपना कनेक्शन जांचें और पुनः प्रयास करें।',
    
    // Training
    'training.myTraining': 'मेरा प्रशिक्षण',
    'training.loadingTrainings': 'आपके प्रशिक्षण लोड हो रहे हैं...',
    'training.new': 'नया',
    'training.active': 'सक्रिय',
    'training.done': 'पूर्ण',
    'training.all': 'सभी',
    'training.unnamed': 'अनाम प्रशिक्षण',
    'training.noDescription': 'कोई विवरण उपलब्ध नहीं',
    'training.completedOn': 'पूर्ण किया',
    'training.overdueBy': 'समय सीमा से अधिक',
    'training.days': 'दिन',
    'training.dueToday': 'आज देय',
    'training.dueIn': 'देय है',
    'training.difficulty': 'कठिनाई',
    'training.duration': 'अवधि',
    'training.noTrainings': 'कोई प्रशिक्षण नहीं मिला',
    'training.trySwitching': 'दूसरे टैब पर स्विच करने का प्रयास करें',
    
    // Training Detail
    'trainingDetail.back': 'वापस',
    'trainingDetail.trainingDetails': 'प्रशिक्षण विवरण',
    'trainingDetail.notFound': 'प्रशिक्षण नहीं मिला',
    'trainingDetail.yourProgress': 'आपकी प्रगति',
    'trainingDetail.completion': 'पूर्णता',
    'trainingDetail.updateProgress': 'अपनी प्रगति अपडेट करें:',
    'trainingDetail.markComplete': 'पूर्ण के रूप में चिह्नित करें',
    'trainingDetail.completedOn': 'पूर्ण किया',
    'trainingDetail.trainingContent': 'प्रशिक्षण सामग्री',
    'trainingDetail.noContent': 'कोई सामग्री उपलब्ध नहीं',
    'trainingDetail.watchVideo': 'प्रशिक्षण वीडियो देखें',
    'trainingDetail.trainingInfo': 'प्रशिक्षण जानकारी',
    'trainingDetail.assignedOn': 'निर्धारित किया:',
    'trainingDetail.dueDate': 'समय सीमा:',
    'trainingDetail.daysOverdue': 'दिन विलंबित',
    'trainingDetail.daysRemaining': 'दिन शेष',
    'trainingDetail.shareFeedback': 'प्रशिक्षण पर फ़ीडबैक साझा करें',
    'trainingDetail.completeToFeedback': 'फ़ीडबैक देने के लिए प्रशिक्षण पूरा करें',
    
    // Training Feedback
    'feedback.trainingComplete': 'प्रशिक्षण पूर्ण!',
    'feedback.rateTraining': 'आप इस प्रशिक्षण को कैसे रेट करेंगे?',
    'feedback.tapToRate': 'रेट करने के लिए टैप करें',
    'feedback.poor': 'खराब',
    'feedback.fair': 'ठीक',
    'feedback.good': 'अच्छा',
    'feedback.veryGood': 'बहुत अच्छा',
    'feedback.excellent': 'उत्कृष्ट',
    'feedback.helpSolve': 'क्या इससे आपकी समस्या हल हुई?',
    'feedback.yes': 'हां',
    'feedback.no': 'नहीं',
    'feedback.additionalFeedback': 'कोई अतिरिक्त फ़ीडबैक?',
    'feedback.optional': 'वैकल्पिक',
    'feedback.placeholder': 'अपने विचार, सुझाव या जो आपने सीखा वह साझा करें...',
    'feedback.submitButton': 'फ़ीडबैक जमा करें',
    'feedback.submittingButton': 'जमा किया जा रहा है...',
    'feedback.provideRating': 'कृपया एक रेटिंग प्रदान करें और बताएं कि क्या प्रशिक्षण सहायक था',
    'feedback.thankYou': 'धन्यवाद!',
    'feedback.submitted': 'आपकी फ़ीडबैक जमा कर दी गई है',
    'feedback.submissionFailed': 'जमा करना विफल',
    'feedback.missingInfo': 'आवश्यक जानकारी गायब है',
    'feedback.completeForm': 'कृपया फॉर्म पूरा करें',
    'feedback.ratingRequired': 'रेटिंग और सहायकता आवश्यक है',
    
    // Tutorial
    'tutorial.skipTutorial': 'ट्यूटोरियल छोड़ें',
    'tutorial.of': 'का',
    'tutorial.previous': 'पिछला',
    'tutorial.next': 'अगला',
    'tutorial.getStarted': 'शुरू करें',
    'tutorial.welcome.title': 'टीचर वॉइस में आपका स्वागत है',
    'tutorial.welcome.desc': 'स्कूल की समस्याओं की रिपोर्ट करने और उनके समाधान को ट्रैक करने के लिए आपका मंच।',
    'tutorial.reporting.title': 'समस्या दर्ज करना',
    'tutorial.reporting.desc': 'स्कूल संबंधी समस्याओं को जमा करने और ट्रैक करने का तरीका जानें।',
    'tutorial.training.title': 'प्रशिक्षण मॉड्यूल',
    'tutorial.training.desc': 'अपनी निर्धारित प्रशिक्षण सामग्री तक पहुंचें और पूरा करें।',
    'tutorial.history.title': 'आपका इतिहास',
    'tutorial.history.desc': 'अपनी सभी जमा की गई फ़ीडबैक और उनकी वर्तमान स्थिति की समीक्षा करें।',
    'tutorial.profile.title': 'प्रोफ़ाइल और सेटिंग्स',
    'tutorial.profile.desc': 'अपने अनुभव को अनुकूलित करें और अपनी प्रोफ़ाइल प्रबंधित करें।',
    'tutorial.feedback.title': 'फ़ीडबैक प्रदान करना',
    'tutorial.feedback.desc': 'पूर्ण प्रशिक्षणों पर अपने विचार साझा करें।',
    
    // Settings (additional)
    'settings.preferences': 'प्राथमिकताएं',
    'settings.darkMode': 'डार्क मोड',
    'settings.useDarkTheme': 'डार्क थीम का उपयोग करें',
    'settings.notifications': 'सूचनाएं',
    'settings.receiveUpdates': 'स्थिति अपडेट प्राप्त करें',
    'settings.supportInfo': 'समर्थन और जानकारी',
    'settings.appTutorial': 'ऐप ट्यूटोरियल',
    'settings.contactSupport': 'समर्थन से संपर्क करें',
    'settings.privacyPolicy': 'गोपनीयता नीति',
    'settings.version': 'टीचर वॉइस v1.0.0',
    'settings.loggedOut': 'लॉग आउट किया गया',
    'settings.logoutSuccess': 'आप सफलतापूर्वक लॉग आउट हो गए हैं।',
      
    'profile.editProfile': 'प्रोफ़ाइल संपादित करें',
    'profile.changePhoto': 'फोटो बदलने के लिए टैप करें',
    'profile.personalInfo': 'व्यक्तिगत जानकारी',
    'profile.fullName': 'पूरा नाम',
    'profile.fullNamePlaceholder': 'अपना पूरा नाम दर्ज करें',
    'profile.emailAddress': 'ईमेल पता',
    'profile.emailPlaceholder': 'अपना ईमेल दर्ज करें',
    'profile.emailCannotChange': 'ईमेल नहीं बदला जा सकता',
    'profile.phoneNumber': 'फ़ोन नंबर',
    'profile.phonePlaceholder': 'अपना फ़ोन नंबर दर्ज करें',
    'profile.bio': 'परिचय',
    'profile.bioPlaceholder': 'अपने बारे में बताएं...',
    'profile.professionalInfo': 'व्यावसायिक जानकारी',
    'profile.qualification': 'योग्यता',
    'profile.qualificationPlaceholder': 'आपकी योग्यता',
    'profile.experience': 'अनुभव के वर्ष',
    'profile.experiencePlaceholder': 'अनुभव के वर्ष',
    'profile.subjects': 'पढ़ाए गए विषय',
    'profile.subjectsPlaceholder': 'आप जो विषय पढ़ाते हैं',
    'profile.assignedCluster': 'निर्धारित क्लस्टर',
    'profile.clusterPlaceholder': 'आपका निर्धारित क्लस्टर',
    'profile.contactAdminCluster': 'क्लस्टर बदलने के लिए व्यवस्थापक से संपर्क करें',
    'profile.updateSuccess': 'प्रोफ़ाइल अपडेट की गई',
    'profile.updateSuccessMsg': 'आपकी प्रोफ़ाइल सफलतापूर्वक अपडेट कर दी गई है।',

    // Navigation
    'nav.dashboard': 'डैशबोर्ड',
    'nav.report': 'समस्या दर्ज करें',
    'nav.history': 'इतिहास',
    'nav.training': 'प्रशिक्षण',
    'nav.settings': 'सेटिंग्स',
    
    // Dashboard
    'dashboard.welcome': 'स्वागत है',
    'dashboard.pending': 'लंबित',
    'dashboard.resolved': 'हल हो गया',
    'dashboard.training': 'प्रशिक्षण',
    'dashboard.recentIssues': 'हाल की समस्याएं',
    'dashboard.noIssues': 'अभी तक कोई समस्या दर्ज नहीं की गई',
    'dashboard.viewAll': 'सभी देखें',
    'dashboard.quickActions': 'त्वरित कार्य',
    'dashboard.reportNew': 'समस्या दर्ज करें',
    'dashboard.viewHistory': 'इतिहास देखें',
    'dashboard.reviewed': 'समीक्षित',
    'dashboard.recentActivity': 'हाल की गतिविधि',
    
    // Report Issue
    'report.title': 'समस्या दर्ज करें',
    'report.subtitle': 'अपनी चुनौती का विवरण दें',
    'report.cluster': 'क्लस्टर',
    'report.category': 'श्रेणी',
    'report.description': 'विवरण',
    'report.submit': 'रिपोर्ट जमा करें',
    'report.success': 'समस्या दर्ज की गई',
    'report.successMsg': 'आपकी समस्या सफलतापूर्वक जमा कर दी गई है',
    
    // Categories
    'category.academic': 'शैक्षणिक',
    'category.infrastructure': 'बुनियादी ढांचा',
    'category.administrative': 'प्रशासनिक',
    'category.safety': 'सुरक्षा',
    'category.technology': 'प्रौद्योगिकी',
    'category.other': 'अन्य',
    
    // Status
    'status.pending': 'लंबित',
    'status.reviewed': 'समीक्षित',
    'status.resolved': 'हल हो गया',
    'status.training_assigned': 'प्रशिक्षण दिया गया',
    
    // Training
    'training.title': 'मेरा प्रशिक्षण',
    'training.subtitle': 'आपके लिए निर्धारित प्रशिक्षण मॉड्यूल',
    'training.notStarted': 'शुरू नहीं हुआ',
    'training.inProgress': 'प्रगति में',
    'training.completed': 'पूर्ण',
    'training.noTraining': 'अभी तक कोई प्रशिक्षण नहीं दिया गया',
    'training.startTraining': 'प्रशिक्षण शुरू करें',
    'training.continueTraining': 'प्रशिक्षण जारी रखें',
    'training.viewDetails': 'विवरण देखें',
    'training.dueDate': 'समय सीमा',
    'training.progress': 'प्रगति',
    
    // Settings
    'settings.title': 'सेटिंग्स',
    'settings.profile': 'प्रोफ़ाइल',
    'settings.language': 'भाषा',
    'settings.selectLanguage': 'भाषा चुनें',
    'settings.name': 'नाम',
    'settings.email': 'ईमेल',
    'settings.cluster': 'क्लस्टर',
    'settings.employeeId': 'कर्मचारी आईडी',
    'settings.logout': 'लॉग आउट',
    'settings.editProfile': 'प्रोफ़ाइल संपादित करें',
    
    // Common
    'common.back': 'वापस',
    'common.cancel': 'रद्द करें',
    'common.save': 'सहेजें',
    'common.delete': 'हटाएं',
    'common.edit': 'संपादित करें',
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'त्रुटि',
    'common.success': 'सफलता',
    'common.viewDetails': 'विवरण देखें',
    'common.close': 'बंद करें',
    'common.saving': 'सहेजा जा रहा है...',
  },
  
  kn: {

    // Issue/Feedback Detail
    'issue.details': 'ಸಮಸ್ಯೆ ವಿವರಗಳು',
    'issue.recommendedTraining': 'ಶಿಫಾರಸು ಮಾಡಿದ ತರಬೇತಿ',
    'issue.findingModule': 'ಉತ್ತಮ ಮಾಡ್ಯೂಲ್ ಹುಡುಕುತ್ತಿದೆ...',
    'issue.basedOnReport': 'ನಿಮ್ಮ ವರದಿಯ ಆಧಾರದ ಮೇಲೆ',
    'issue.startTraining': 'ತರಬೇತಿ ಮಾಡ್ಯೂಲ್ ಪ್ರಾರಂಭಿಸಿ',
    'issue.yourReport': 'ನಿಮ್ಮ ವರದಿ',
    
    // History
    'history.title': 'ನನ್ನ ಪ್ರತಿಕ್ರಿಯೆ',
    'history.issues': 'ಸಮಸ್ಯೆಗಳು',
    'history.issue': 'ಸಮಸ್ಯೆ',
    'history.allStatus': 'ಎಲ್ಲಾ ಸ್ಥಿತಿ',
    'history.filter': 'ಫಿಲ್ಟರ್',
    'history.trainingAssigned': 'ತರಬೇತಿ ನಿಯೋಜಿಸಲಾಗಿದೆ',
    'history.noFeedback': 'ಇನ್ನೂ ಪ್ರತಿಕ್ರಿಯೆ ಇಲ್ಲ',
    'history.noMatching': 'ಹೊಂದಾಣಿಕೆಯ ಪ್ರತಿಕ್ರಿಯೆ ಇಲ್ಲ',
    'history.startReporting': 'ನಿಮ್ಮ ಮೊದಲ ಸಮಸ್ಯೆಯನ್ನು ವರದಿ ಮಾಡುವ ಮೂಲಕ ಪ್ರಾರಂಭಿಸಿ',
    'history.tryFilter': 'ಹೆಚ್ಚಿನ ಫಲಿತಾಂಶಗಳನ್ನು ನೋಡಲು ಫಿಲ್ಟರ್ ಬದಲಾಯಿಸಲು ಪ್ರಯತ್ನಿಸಿ',
    'history.reportIssue': 'ಸಮಸ್ಯೆ ವರದಿ ಮಾಡಿ',
    
    // Login
    'login.title': 'ಗುರುಶಿಕ್ಷಣ',
    'login.subtitle': 'ಶಾಲಾ ಪ್ರತಿಕ್ರಿಯೆ ವ್ಯವಸ್ಥೆ',
    'login.signIn': 'ಸೈನ್ ಇನ್',
    'login.enterCredentials': 'ಮುಂದುವರಿಯಲು ನಿಮ್ಮ ರುಜುವಾತುಗಳನ್ನು ನಮೂದಿಸಿ',
    'login.email': 'ಇಮೇಲ್',
    'login.emailPlaceholder': 'teacher@school.edu',
    'login.emailRequired': 'ಇಮೇಲ್ ಅಗತ್ಯವಿದೆ',
    'login.emailInvalid': 'ದಯವಿಟ್ಟು ಮಾನ್ಯ ಇಮೇಲ್ ನಮೂದಿಸಿ',
    'login.password': 'ಪಾಸ್‌ವರ್ಡ್',
    'login.passwordPlaceholder': 'ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ',
    'login.passwordRequired': 'ಪಾಸ್‌ವರ್ಡ್ ಅಗತ್ಯವಿದೆ',
    'login.passwordMin': 'ಪಾಸ್‌ವರ್ಡ್ ಕನಿಷ್ಟ 4 ಅಕ್ಷರಗಳಾಗಿರಬೇಕು',
    'login.signingIn': 'ಸೈನ್ ಇನ್ ಆಗುತ್ತಿದೆ...',
    'login.signInButton': 'ಸೈನ್ ಇನ್',
    'login.demoHint': 'ಲಾಗಿನ್ ಮಾಡಲು ಯಾವುದೇ ಇಮೇಲ್ ಮತ್ತು ಪಾಸ್‌ವರ್ಡ್ (ಕನಿಷ್ಟ 4 ಅಕ್ಷರಗಳು) ಬಳಸಿ',
    'login.welcomeBack': 'ಮತ್ತೆ ಸ್ವಾಗತ!',
    'login.loginSuccess': 'ನೀವು ಯಶಸ್ವಿಯಾಗಿ ಲಾಗಿನ್ ಆಗಿದ್ದೀರಿ.',
    'login.loginFailed': 'ಲಾಗಿನ್ ವಿಫಲವಾಗಿದೆ',
    'login.checkCredentials': 'ದಯವಿಟ್ಟು ನಿಮ್ಮ ರುಜುವಾತುಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    'login.connectionError': 'ಸಂಪರ್ಕ ದೋಷ',
    'login.networkError': 'ಸಂಪರ್ಕಿಸಲು ಸಾಧ್ಯವಾಗುತ್ತಿಲ್ಲ. ದಯವಿಟ್ಟು ನಿಮ್ಮ ನೆಟ್‌ವರ್ಕ್ ಪರಿಶೀಲಿಸಿ.',
    
    // Not Found
    'notFound.title': '404',
    'notFound.message': 'ಓಹ್! ಪುಟ ಕಂಡುಬಂದಿಲ್ಲ',
    'notFound.returnHome': 'ಮುಖಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ',
    
    // Onboarding
    'onboarding.skip': 'ಬಿಟ್ಟುಬಿಡಿ',
    'onboarding.next': 'ಮುಂದೆ',
    'onboarding.getStarted': 'ಪ್ರಾರಂಭಿಸಿ',
    'onboarding.slide1.title': 'ಸುಲಭವಾಗಿ ಸಮಸ್ಯೆಗಳನ್ನು ವರದಿ ಮಾಡಿ',
    'onboarding.slide1.desc': 'ನಿಮ್ಮ ಫೋನ್‌ನಿಂದ ನೇರವಾಗಿ ಯಾವುದೇ ಶಾಲಾ ಸಂಬಂಧಿತ ಸಮಸ್ಯೆಗಳ ಬಗ್ಗೆ ಪ್ರತಿಕ್ರಿಯೆ ಸಲ್ಲಿಸಿ. ಶೈಕ್ಷಣಿಕ, ಮೂಲಸೌಕರ್ಯ, ಸುರಕ್ಷತೆ – ನಾವು ಎಲ್ಲವನ್ನೂ ಒಳಗೊಂಡಿದ್ದೇವೆ.',
    'onboarding.slide2.title': 'ನಿಮ್ಮ ಸಲ್ಲಿಕೆಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    'onboarding.slide2.desc': 'ನಿಮ್ಮ ವರದಿ ಮಾಡಿದ ಸಮಸ್ಯೆಗಳ ಸ್ಥಿತಿಯ ಬಗ್ಗೆ ತಿಳುವಳಿಕೆ ಪಡೆಯಿರಿ. ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಪರಿಶೀಲಿಸುತ್ತಿರುವಾಗ ಅಥವಾ ಪರಿಹರಿಸುತ್ತಿರುವಾಗ ನವೀಕರಣಗಳನ್ನು ಪಡೆಯಿರಿ.',
    'onboarding.slide3.title': 'ನೈಜ-ಸಮಯ ನವೀಕರಣಗಳು',
    'onboarding.slide3.desc': 'ನಿಮ್ಮ ಸಲ್ಲಿಸಿದ ಪ್ರತಿಕ್ರಿಯೆಯಲ್ಲಿ ನವೀಕರಣಗಳು ಇದ್ದಾಗ ಅಧಿಸೂಚನೆಗಳನ್ನು ಸ್ವೀಕರಿಸಿ. ಸ್ಥಿತಿಯ ಬಗ್ಗೆ ಇನ್ನು ಆಶ್ಚರ್ಯಪಡಬೇಡಿ.',
    'onboarding.slide4.title': 'ಫಲಿತಾಂಶಗಳನ್ನು ನೋಡಿ',
    'onboarding.slide4.desc': 'ಪರಿಹಾರ ವಿವರಗಳು ಮತ್ತು ನಿರ್ವಾಹಕ ಟಿಪ್ಪಣಿಗಳನ್ನು ವೀಕ್ಷಿಸಿ. ನಿಮ್ಮ ಧ್ವನಿ ಮಹತ್ವದ್ದಾಗಿದೆ ಮತ್ತು ಶಾಲೆಯಲ್ಲಿ ನೈಜ ಸುಧಾರಣೆಗಳಿಗೆ ಕಾರಣವಾಗುತ್ತದೆ.',
    
    // Report Issue
    'report.reportingAs': 'ಈ ರೀತಿ ವರದಿ ಮಾಡುತ್ತಿದ್ದೇವೆ',
    'report.descriptionLabel': 'ವಿವರಣೆ',
    'report.descriptionPlaceholder': 'ಸಮಸ್ಯೆಯನ್ನು ವಿವರವಾಗಿ ವಿವರಿಸಿ...',
    'report.descriptionRequired': 'ವಿವರಣೆ ಅಗತ್ಯವಿದೆ',
    'report.descriptionMin': 'ದಯವಿಟ್ಟು ಕನಿಷ್ಟ 20 ಅಕ್ಷರಗಳನ್ನು ಒದಗಿಸಿ',
    'report.categoryRequired': 'ದಯವಿಟ್ಟು ವರ್ಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'report.submitButton': 'ಸಮಸ್ಯೆ ಸಲ್ಲಿಸಿ',
    'report.submitting': 'ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...',
    'report.alreadyAssigned': 'ತರಬೇತಿ ಈಗಾಗಲೇ ನಿಯೋಜಿಸಲಾಗಿದೆ!',
    'report.checkTraining': 'ಮುಂದುವರಿಯಲು ನಿಮ್ಮ ತರಬೇತಿ ಟ್ಯಾಬ್ ಪರಿಶೀಲಿಸಿ.',
    'report.issueReported': 'ಸಮಸ್ಯೆ ವರದಿ ಮಾಡಲಾಗಿದೆ!',
    'report.submittedSuccess': 'ನಿಮ್ಮ ಸಮಸ್ಯೆಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಸಲಾಗಿದೆ.',
    'report.personalizedAssigned': 'ವೈಯಕ್ತಿಕೀಕರಿಸಿದ ತರಬೇತಿ ನಿಯೋಜಿಸಲಾಗಿದೆ!',
    'report.submitSuccess': 'ಸಮಸ್ಯೆಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ವರದಿ ಮಾಡಲಾಗಿದೆ!',
    'report.submitFailed': 'ಸಲ್ಲಿಸಲು ವಿಫಲವಾಗಿದೆ',
    'report.checkConnection': 'ದಯವಿಟ್ಟು ನಿಮ್ಮ ಸಂಪರ್ಕವನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    
    // Training
    'training.myTraining': 'ನನ್ನ ತರಬೇತಿ',
    'training.loadingTrainings': 'ನಿಮ್ಮ ತರಬೇತಿಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    'training.new': 'ಹೊಸ',
    'training.active': 'ಸಕ್ರಿಯ',
    'training.done': 'ಮುಗಿದಿದೆ',
    'training.all': 'ಎಲ್ಲಾ',
    'training.unnamed': 'ಹೆಸರಿಲ್ಲದ ತರಬೇತಿ',
    'training.noDescription': 'ಯಾವುದೇ ವಿವರಣೆ ಲಭ್ಯವಿಲ್ಲ',
    'training.completedOn': 'ಪೂರ್ಣಗೊಂಡಿದೆ',
    'training.overdueBy': 'ಮುಕ್ತಾಯ ದಿನಾಂಕ ದಾಟಿದೆ',
    'training.days': 'ದಿನಗಳು',
    'training.dueToday': 'ಇಂದು ಮುಕ್ತಾಯ',
    'training.dueIn': 'ಮುಕ್ತಾಯವಾಗಲಿದೆ',
    'training.difficulty': 'ಕಷ್ಟತೆ',
    'training.duration': 'ಅವಧಿ',
    'training.noTrainings': 'ತರಬೇತಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    'training.trySwitching': 'ಬೇರೆ ಟ್ಯಾಬ್‌ಗೆ ಬದಲಾಯಿಸಲು ಪ್ರಯತ್ನಿಸಿ',
    
    // Training Detail
    'trainingDetail.back': 'ಹಿಂದೆ',
    'trainingDetail.trainingDetails': 'ತರಬೇತಿ ವಿವರಗಳು',
    'trainingDetail.notFound': 'ತರಬೇತಿ ಕಂಡುಬಂದಿಲ್ಲ',
    'trainingDetail.yourProgress': 'ನಿಮ್ಮ ಪ್ರಗತಿ',
    'trainingDetail.completion': 'ಪೂರ್ಣಗೊಳಿಸುವಿಕೆ',
    'trainingDetail.updateProgress': 'ನಿಮ್ಮ ಪ್ರಗತಿಯನ್ನು ನವೀಕರಿಸಿ:',
    'trainingDetail.markComplete': 'ಪೂರ್ಣಗೊಂಡಂತೆ ಗುರುತಿಸಿ',
    'trainingDetail.completedOn': 'ಪೂರ್ಣಗೊಂಡಿದೆ',
    'trainingDetail.trainingContent': 'ತರಬೇತಿ ವಿಷಯ',
    'trainingDetail.noContent': 'ವಿಷಯ ಲಭ್ಯವಿಲ್ಲ',
    'trainingDetail.watchVideo': 'ತರಬೇತಿ ವೀಡಿಯೋ ವೀಕ್ಷಿಸಿ',
    'trainingDetail.trainingInfo': 'ತರಬೇತಿ ಮಾಹಿತಿ',
    'trainingDetail.assignedOn': 'ನಿಯೋಜಿಸಲಾಗಿದೆ:',
    'trainingDetail.dueDate': 'ಮುಕ್ತಾಯ ದಿನಾಂಕ:',
    'trainingDetail.daysOverdue': 'ದಿನಗಳು ವಿಳಂಬವಾಗಿದೆ',
    'trainingDetail.daysRemaining': 'ದಿನಗಳು ಉಳಿದಿವೆ',
    'trainingDetail.shareFeedback': 'ತರಬೇತಿಯ ಬಗ್ಗೆ ಪ್ರತಿಕ್ರಿಯೆ ಹಂಚಿಕೊಳ್ಳಿ',
    'trainingDetail.completeToFeedback': 'ಪ್ರತಿಕ್ರಿಯೆ ನೀಡಲು ತರಬೇತಿ ಪೂರ್ಣಗೊಳಿಸಿ',
    
    // Training Feedback
    'feedback.trainingComplete': 'ತರಬೇತಿ ಪೂರ್ಣಗೊಂಡಿದೆ!',
    'feedback.rateTraining': 'ನೀವು ಈ ತರಬೇತಿಯನ್ನು ಹೇಗೆ ರೇಟ್ ಮಾಡುತ್ತೀರಿ?',
    'feedback.tapToRate': 'ರೇಟ್ ಮಾಡಲು ಟ್ಯಾಪ್ ಮಾಡಿ',
    'feedback.poor': 'ಕಳಪೆ',
    'feedback.fair': 'ಸರಿಯಾದ',
    'feedback.good': 'ಒಳ್ಳೆಯದು',
    'feedback.veryGood': 'ತುಂಬಾ ಒಳ್ಳೆಯದು',
    'feedback.excellent': 'ಅತ್ಯುತ್ತಮ',
    'feedback.helpSolve': 'ಇದು ನಿಮ್ಮ ಸಮಸ್ಯೆಯನ್ನು ಪರಿಹರಿಸಲು ಸಹಾಯ ಮಾಡಿತೇ?',
    'feedback.yes': 'ಹೌದು',
    'feedback.no': 'ಇಲ್ಲ',
    'feedback.additionalFeedback': 'ಯಾವುದಾದರೂ ಹೆಚ್ಚುವರಿ ಪ್ರತಿಕ್ರಿಯೆ?',
    'feedback.optional': 'ಐಚ್ಛಿಕ',
    'feedback.placeholder': 'ನಿಮ್ಮ ಆಲೋಚನೆಗಳು, ಸಲಹೆಗಳು ಅಥವಾ ನೀವು ಕಲಿತದನ್ನು ಹಂಚಿಕೊಳ್ಳಿ...',
    'feedback.submitButton': 'ಪ್ರತಿಕ್ರಿಯೆ ಸಲ್ಲಿಸಿ',
    'feedback.submittingButton': 'ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...',
    'feedback.provideRating': 'ದಯವಿಟ್ಟು ರೇಟಿಂಗ್ ಒದಗಿಸಿ ಮತ್ತು ತರಬೇತಿ ಸಹಾಯಕವಾಗಿದೆಯೇ ಎಂದು ಸೂಚಿಸಿ',
    'feedback.thankYou': 'ಧನ್ಯವಾದಗಳು!',
    'feedback.submitted': 'ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆ ಸಲ್ಲಿಸಲಾಗಿದೆ',
    'feedback.submissionFailed': 'ಸಲ್ಲಿಸುವಿಕೆ ವಿಫಲವಾಗಿದೆ',
    'feedback.missingInfo': 'ಅಗತ್ಯ ಮಾಹಿತಿ ಕಾಣೆಯಾಗಿದೆ',
    'feedback.completeForm': 'ದಯವಿಟ್ಟು ಫಾರ್ಮ್ ಪೂರ್ಣಗೊಳಿಸಿ',
    'feedback.ratingRequired': 'ರೇಟಿಂಗ್ ಮತ್ತು ಸಹಾಯಕತೆ ಅಗತ್ಯವಿದೆ',
    
    // Tutorial
    'tutorial.skipTutorial': 'ಟ್ಯುಟೋರಿಯಲ್ ಬಿಟ್ಟುಬಿಡಿ',
    'tutorial.of': 'ರಲ್ಲಿ',
    'tutorial.previous': 'ಹಿಂದಿನದು',
    'tutorial.next': 'ಮುಂದೆ',
    'tutorial.getStarted': 'ಪ್ರಾರಂಭಿಸಿ',
    'tutorial.welcome.title': 'ಟೀಚರ್ ವಾಯ್ಸ್‌ಗೆ ಸ್ವಾಗತ',
    'tutorial.welcome.desc': 'ಶಾಲಾ ಸಮಸ್ಯೆಗಳನ್ನು ವರದಿ ಮಾಡಲು ಮತ್ತು ಅವುಗಳ ಪರಿಹಾರವನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ನಿಮ್ಮ ವೇದಿಕೆ.',
    'tutorial.reporting.title': 'ಸಮಸ್ಯೆಗಳನ್ನು ವರದಿ ಮಾಡುವುದು',
    'tutorial.reporting.desc': 'ಶಾಲಾ ಸಂಬಂಧಿತ ಸಮಸ್ಯೆಗಳನ್ನು ಸಲ್ಲಿಸುವುದು ಮತ್ತು ಟ್ರ್ಯಾಕ್ ಮಾಡುವುದು ಹೇಗೆ ಎಂದು ತಿಳಿಯಿರಿ.',
    'tutorial.training.title': 'ತರಬೇತಿ ಮಾಡ್ಯೂಲ್‌ಗಳು',
    'tutorial.training.desc': 'ನಿಮ್ಮ ನಿಯೋಜಿತ ತರಬೇತಿ ಸಾಮಗ್ರಿಗಳನ್ನು ಪ್ರವೇಶಿಸಿ ಮತ್ತು ಪೂರ್ಣಗೊಳಿಸಿ.',
    'tutorial.history.title': 'ನಿಮ್ಮ ಇತಿಹಾಸ',
    'tutorial.history.desc': 'ನಿಮ್ಮ ಎಲ್ಲಾ ಸಲ್ಲಿಸಿದ ಪ್ರತಿಕ್ರಿಯೆ ಮತ್ತು ಅವುಗಳ ಪ್ರಸ್ತುತ ಸ್ಥಿತಿಯನ್ನು ಪರಿಶೀಲಿಸಿ.',
    'tutorial.profile.title': 'ಪ್ರೊಫೈಲ್ ಮತ್ತು ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'tutorial.profile.desc': 'ನಿಮ್ಮ ಅನುಭವವನ್ನು ಕಸ್ಟಮೈಸ್ ಮಾಡಿ ಮತ್ತು ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ನಿರ್ವಹಿಸಿ.',
    'tutorial.feedback.title': 'ಪ್ರತಿಕ್ರಿಯೆ ನೀಡುವುದು',
    'tutorial.feedback.desc': 'ಪೂರ್ಣಗೊಂಡ ತರಬೇತಿಗಳ ಬಗ್ಗೆ ನಿಮ್ಮ ಆಲೋಚನೆಗಳನ್ನು ಹಂಚಿಕೊಳ್ಳಿ.',
    
    // Settings (additional)
    'settings.preferences': 'ಆದ್ಯತೆಗಳು',
    'settings.darkMode': 'ಡಾರ್ಕ್ ಮೋಡ್',
    'settings.useDarkTheme': 'ಡಾರ್ಕ್ ಥೀಮ್ ಬಳಸಿ',
    'settings.notifications': 'ಅಧಿಸೂಚನೆಗಳು',
    'settings.receiveUpdates': 'ಸ್ಥಿತಿ ನವೀಕರಣಗಳನ್ನು ಸ್ವೀಕರಿಸಿ',
    'settings.supportInfo': 'ಬೆಂಬಲ ಮತ್ತು ಮಾಹಿತಿ',
    'settings.appTutorial': 'ಆಪ್ ಟ್ಯುಟೋರಿಯಲ್',
    'settings.contactSupport': 'ಬೆಂಬಲವನ್ನು ಸಂಪರ್ಕಿಸಿ',
    'settings.privacyPolicy': 'ಗೌಪ್ಯತಾ ನೀತಿ',
    'settings.version': 'ಟೀಚರ್ ವಾಯ್ಸ್ v1.0.0',
    'settings.loggedOut': 'ಲಾಗ್ ಔಟ್ ಆಗಿದೆ',
    'settings.logoutSuccess': 'ನೀವು ಯಶಸ್ವಿಯಾಗಿ ಲಾಗ್ ಔಟ್ ಆಗಿದ್ದೀರಿ.',
    'profile.editProfile': 'ಪ್ರೊಫೈಲ್ ಎಡಿಟ್ ಮಾಡಿ',
    'profile.changePhoto': 'ಫೋಟೋ ಬದಲಾಯಿಸಲು ಟ್ಯಾಪ್ ಮಾಡಿ',
    'profile.personalInfo': 'ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ',
    'profile.fullName': 'ಪೂರ್ಣ ಹೆಸರು',
    'profile.fullNamePlaceholder': 'ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರು ನಮೂದಿಸಿ',
    'profile.emailAddress': 'ಇಮೇಲ್ ವಿಳಾಸ',
    'profile.emailPlaceholder': 'ನಿಮ್ಮ ಇಮೇಲ್ ನಮೂದಿಸಿ',
    'profile.emailCannotChange': 'ಇಮೇಲ್ ಬದಲಾಯಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ',
    'profile.phoneNumber': 'ಫೋನ್ ಸಂಖ್ಯೆ',
    'profile.phonePlaceholder': 'ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
    'profile.bio': 'ಪರಿಚಯ',
    'profile.bioPlaceholder': 'ನಿಮ್ಮ ಬಗ್ಗೆ ತಿಳಿಸಿ...',
    'profile.professionalInfo': 'ವೃತ್ತಿಪರ ಮಾಹಿತಿ',
    'profile.qualification': 'ಅರ್ಹತೆ',
    'profile.qualificationPlaceholder': 'ನಿಮ್ಮ ಅರ್ಹತೆಗಳು',
    'profile.experience': 'ಅನುಭವದ ವರ್ಷಗಳು',
    'profile.experiencePlaceholder': 'ಅನುಭವದ ವರ್ಷಗಳು',
    'profile.subjects': 'ಕಲಿಸಿದ ವಿಷಯಗಳು',
    'profile.subjectsPlaceholder': 'ನೀವು ಕಲಿಸುವ ವಿಷಯಗಳು',
    'profile.assignedCluster': 'ನಿಯೋಜಿತ ಕ್ಲಸ್ಟರ್',
    'profile.clusterPlaceholder': 'ನಿಮ್ಮ ನಿಯೋಜಿತ ಕ್ಲಸ್ಟರ್',
    'profile.contactAdminCluster': 'ಕ್ಲಸ್ಟರ್ ಬದಲಾಯಿಸಲು ನಿರ್ವಾಹಕರನ್ನು ಸಂಪರ್ಕಿಸಿ',
    'profile.updateSuccess': 'ಪ್ರೊಫೈಲ್ ನವೀಕರಿಸಲಾಗಿದೆ',
    'profile.updateSuccessMsg': 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಅನ್ನು ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ.',

    // Navigation
    'nav.dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'nav.report': 'ಸಮಸ್ಯೆ ವರದಿ ಮಾಡಿ',
    'nav.history': 'ಇತಿಹಾಸ',
    'nav.training': 'ತರಬೇತಿ',
    'nav.settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    
    // Dashboard
    'dashboard.welcome': 'ಸ್ವಾಗತ',
    'dashboard.pending': 'ಬಾಕಿ ಉಳಿದಿದೆ',
    'dashboard.resolved': 'ಪರಿಹರಿಸಲಾಗಿದೆ',
    'dashboard.training': 'ತರಬೇತಿ',
    'dashboard.recentIssues': 'ಇತ್ತೀಚಿನ ಸಮಸ್ಯೆಗಳು',
    'dashboard.noIssues': 'ಇನ್ನೂ ಯಾವುದೇ ಸಮಸ್ಯೆಗಳನ್ನು ವರದಿ ಮಾಡಲಾಗಿಲ್ಲ',
    'dashboard.viewAll': 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ',
    'dashboard.quickActions': 'ತ್ವರಿತ ಕ್ರಿಯೆಗಳು',
    'dashboard.viewHistory': 'ಇತಿಹಾಸ ವೀಕ್ಷಿಸಿ',
    'dashboard.reviewed': 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    'dashboard.reportNew': 'ಸಮಸ್ಯೆ ವರದಿ ಮಾಡಿ',
    'dashboard.recentActivity': 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ',
    
    // Report Issue
    'report.title': 'ಸಮಸ್ಯೆ ವರದಿ ಮಾಡಿ',
    'report.subtitle': 'ನಿಮ್ಮ ಸವಾಲನ್ನು ವಿವರಿಸಿ',
    'report.cluster': 'ಕ್ಲಸ್ಟರ್',
    'report.category': 'ವರ್ಗ',
    'report.description': 'ವಿವರಣೆ',
    'report.submit': 'ವರದಿ ಸಲ್ಲಿಸಿ',
    'report.success': 'ಸಮಸ್ಯೆ ವರದಿ ಮಾಡಲಾಗಿದೆ',
    'report.successMsg': 'ನಿಮ್ಮ ಸಮಸ್ಯೆಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಸಲಾಗಿದೆ',
    
    // Categories
    'category.academic': 'ಶೈಕ್ಷಣಿಕ',
    'category.infrastructure': 'ಮೂಲಸೌಕರ್ಯ',
    'category.administrative': 'ಆಡಳಿತಾತ್ಮಕ',
    'category.safety': 'ಸುರಕ್ಷತೆ',
    'category.technology': 'ತಂತ್ರಜ್ಞಾನ',
    'category.other': 'ಇತರೆ',
    
    // Status
    'status.pending': 'ಬಾಕಿ ಉಳಿದಿದೆ',
    'status.reviewed': 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    'status.resolved': 'ಪರಿಹರಿಸಲಾಗಿದೆ',
    'status.training_assigned': 'ತರಬೇತಿ ನಿಯೋಜಿಸಲಾಗಿದೆ',
    
    // Training
    'training.title': 'ನನ್ನ ತರಬೇತಿ',
    'training.subtitle': 'ನಿಮಗೆ ನಿಯೋಜಿಸಿದ ತರಬೇತಿ ಮಾಡ್ಯೂಲ್‌ಗಳು',
    'training.notStarted': 'ಪ್ರಾರಂಭವಾಗಿಲ್ಲ',
    'training.inProgress': 'ಪ್ರಗತಿಯಲ್ಲಿದೆ',
    'training.completed': 'ಪೂರ್ಣಗೊಂಡಿದೆ',
    'training.noTraining': 'ಇನ್ನೂ ತರಬೇತಿ ನಿಯೋಜಿಸಲಾಗಿಲ್ಲ',
    'training.startTraining': 'ತರಬೇತಿ ಪ್ರಾರಂಭಿಸಿ',
    'training.continueTraining': 'ತರಬೇತಿ ಮುಂದುವರಿಸಿ',
    'training.viewDetails': 'ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    'training.dueDate': 'ಕೊನೆಯ ದಿನಾಂಕ',
    'training.progress': 'ಪ್ರಗತಿ',
    
    // Settings
    'settings.title': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'settings.profile': 'ಪ್ರೊಫೈಲ್',
    'settings.language': 'ಭಾಷೆ',
    'settings.selectLanguage': 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    'settings.name': 'ಹೆಸರು',
    'settings.email': 'ಇಮೇಲ್',
    'settings.cluster': 'ಕ್ಲಸ್ಟರ್',
    'settings.employeeId': 'ಉದ್ಯೋಗಿ ID',
    'settings.logout': 'ಲಾಗ್ ಔಟ್',
    'settings.editProfile': 'ಪ್ರೊಫೈಲ್ ಎಡಿಟ್ ಮಾಡಿ',
    
    // Common
    'common.back': 'ಹಿಂದೆ',
    'common.cancel': 'ರದ್ದುಗೊಳಿಸಿ',
    'common.save': 'ಉಳಿಸಿ',
    'common.delete': 'ಅಳಿಸಿ',
    'common.edit': 'ಎಡಿಟ್ ಮಾಡಿ',
    'common.loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    'common.error': 'ದೋಷ',
    'common.success': 'ಯಶಸ್ಸು',
    'common.viewDetails': 'ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    'common.close': 'ಮುಚ್ಚಿ',
    'common.saving': 'ಉಳಿಸಲಾಗುತ್ತಿದೆ...',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const { teacher } = useAuth();
    const [language, setLanguageState] = useState<Language>('en');
  
    useEffect(() => {
      const savedLang = localStorage.getItem('preferredLanguage') as Language;
      if (savedLang && ['en', 'hi', 'kn'].includes(savedLang)) {
        setLanguageState(savedLang);
      } else if (teacher?.preferredLanguage) {
        setLanguageState(teacher.preferredLanguage as Language);
      }
    }, [teacher]);
  
    const setLanguage = (lang: Language) => {
      setLanguageState(lang);
      localStorage.setItem('preferredLanguage', lang);
    };
  
    const t = (key: string): string => {
      return translations[language][key] || key;
    };
  
    return (
      <LanguageContext.Provider value={{ language, setLanguage, t }}>
        {children}
      </LanguageContext.Provider>
    );
  };
  
  export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
      throw new Error('useLanguage must be used within LanguageProvider');
    }
    return context;
  };
